name: Windows Build

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset windows-release

      - name: Build
        run: cmake --build --preset windows-release

      - name: Install
        run: cmake --install build/windows-release

      - name: Package
        run: cpack --preset windows-release-package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Project1-Windows
          path: build/windows-release/*.zip