name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:

  build:
    name: ${{ matrix.name }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:

          - name: Linux Release
            preset: linux-release

          - name: Windows Release
            preset: windows-release

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # ------------------------------------------------------
      # Windows cross-compilation dependencies
      # ------------------------------------------------------

      - name: Install Windows Tools
        if: matrix.preset == 'windows-release'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            ntldd
      

      # Linux dev tools

      - name: Install Linux Tools
        if: matrix.preset == 'linux-release'
        run: ./scripts/setup-ubuntu.sh


      # ------------------------------------------------------
      # Configure
      # ------------------------------------------------------

      - name: Configure
        run: |
          cmake --preset ${{ matrix.preset }}


      # ------------------------------------------------------
      # Build
      # ------------------------------------------------------

      - name: Build
        run: |
          cmake --build --preset ${{ matrix.preset }}