name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:

  # ==========================================================
  # Linux
  # ==========================================================

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: ./scripts/setup-ubuntu.sh

      - name: Configure
        run: cmake --preset linux-release

      - name: Build
        run: cmake --build --preset linux-release


  # ==========================================================
  # Windows
  # ==========================================================

  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset windows-release

      - name: Build
        run: cmake --build --preset windows-release